services:
  # 1. データベース
  db:
    image: mysql:8.0
    container_name: life_platter_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  # 2. アプリサーバー (FastAPI)
  app:
    build: .
    container_name: life_platter_app
    depends_on:
      - db
    # environment と volumes は override ファイルで設定

  # 3. Webサーバー (Nginx)
  nginx:
    image: nginx:latest
    container_name: life_platter_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data:
